name: TiddlyPWA
slug: tiddly
description: Run TiddlyWiki PWA server with full offline and sync support via Deno
version: 1.0.29
url: https://github.com/tdangschulz/addon-tiddly
webui: http://[HOST]:[PORT:8000]
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
panel_icon: mdi:web
ports:
  8000/tcp: 8000
options:
  port: 8000
  db_path: "/var/db/tiddly/pwa.db"
  admin_password_hash: ""
  admin_password_salt: ""
schema:
  port: int
  db_path: str
  admin_password_hash: str
  admin_password_salt: str