name: TiddlyPWA
slug: tiddly
description: Run TiddlyWiki PWA server with full offline and sync support via Deno
version: 1.0.36
url: https://github.com/tdangschulz/addon-tiddly
webui: https://[HOST]:[PORT]
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
panel_icon: mdi:web
ports:
  8000/tcp: null
options:
  port: 8000
  db_path: "/var/db/tiddly/pwa.db"
  admin_password_hash: ""
  admin_password_salt: ""
  base_path: ""
  host: ""
schema:
  port: int
  db_path: str
  admin_password_hash: str
  admin_password_salt: str
  base_path: str
  host: str