name: TiddlyPWA
slug: tiddly
description: Run TiddlyWiki PWA server with full offline and sync support via Deno
version: 1.0.58
url: https://github.com/tdangschulz/addon-tiddly
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
panel_icon: mdi:web
map:
  - ssl
ports:
  8443/tcp: 8443
options:
  db_path: "/var/db/tiddly/pwa.db"
  admin_password_hash: ""
  admin_password_salt: ""
  base_path: ""
  host: ""
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  db_path: str
  admin_password_hash: str
  admin_password_salt: str
  ssl: bool
  certfile: str
  keyfile: str
  base_path: str
  host: str
webui: "[PROTO:ssl]://[HOST]:[PORT:8443]"