name: Tiddly Wiki
slug: tiddly
description: Run a self-hosted TiddlyWiki PWA with Deno inside Home Assistant OS
version: 1.0.0
url: https://github.com/tdangschulz/addon-tiddly
webui: http://[HOST]:[PORT:8080]
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
init: false
panel_icon: mdi:book-open-variant
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface (TiddlyWiki PWA server)
map:
  - config:rw
  - share:rw
  - media:rw
  - backup:rw
options:
  port: 8080
  extra_args: ""
schema:
  port: int
  extra_args: str
#image: ghcr.io/<your-username>/tiddlywiki-pwa-{arch}
